### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by gimhanul** [gimhanul/clone-market-kurly#13]
### ✨ Describe

main page를 만들어야 합니다

### ✅ Tasks

- [x] product component
- [x] main banner
- [x] product 캐러셀 component
- [x] product 모음집 한 section component
- [x] dummy data 추가
