### ISSUE TITLE
Product Detail

### ISSUE THREAD

**Issue by gimhanul** [gimhanul/clone-market-kurly#28]
### ✨ Describe

현재 Product Detail은 무조건 감자칩만 보여주고 있습니다.
API 를 구현 안 했으니 데이터 넣어 놓고 id로 꺼내쓰도록 해야 합니다.

### ✅ Tasks

- [x] data 더 넣기
- [x] url parameter로 id 넘겨주기
- [x] 관련 꺼내는 Logic
- [x] 장바구니 관련 버그 fix
